### ISSUE TITLE
Different color for comments

### ISSUE THREAD

**Issue by quantenProjects** [burodepeper/minimal-syntax#13]
The color for comments is very similar to the color of the line numbers of changed lines.

The color of the lines number is controlled by the VCS (git) and can be dark grey, green for added lines and orange for changed lines.

When you have a block, that was changed (or added, sometimes, git marks lines as changed, even if they are new) it has a quite different sight as a new added comment or a unchanged comment.

You have to decide if you want to change it, but in my view, it would enhance the readability a bit more.

I really like this theme, because of its simplicity. Thank you

**Comment by burodepeper** [comment]
Could you post some screenshots? It could be that minimal-syntax and your ui theme are in conflict here.

**Comment by quantenProjects** [comment]
Here are two example screenshots from assembly and php

![assembly](https://user-images.githubusercontent.com/10087242/41220526-fdf6e7d8-6d61-11e8-97f0-3a1ad72d3c0a.png)
![php](https://user-images.githubusercontent.com/10087242/41220538-01abed38-6d62-11e8-8039-a7b0fdddfa21.png)

The appearance of the line numbers doesn't change, when I change the UI theme (btw, it is One Light).

I took a look inside this theme and found this: https://github.com/burodepeper/minimal-syntax/blob/6bcf647c9ba43cd01cfcfac37661dec2ae7974d2/styles/editor.less#L120-L129

So it is by design so, that this theme uses the same color for comments as well as for changed lines. I would like to have another color for comments to not get confused, but this is completely up to you.

Decide how you want to have this, I only wanted to point this out and discuss about it

**Comment by burodepeper** [comment]
> Decide how you want to have this, I only wanted to point this out and discuss about it

I intend to keep it like this. The added lines are also same green as used by the theme, etc. It is rather arbitrary for you to change this yourself in a custom stylesheet. Have you looked into that?

**Comment by quantenProjects** [comment]
Now I did, I will customize it for myself.

Thanks for the support
